export const LANGUAGES = {
  af: 'Afrikaans (Afrikaans)',
  sq: 'Albanian (Shqip)',
  ar: 'Arabic (&#x639;&#x631;&#x628;&#x64A;)',
  an: 'Aragonese (Aragon&eacute;s)',
  hy: 'Armenian (&#x540;&#x561;&#x575;&#x565;&#x580;&#x565;&#x576;)',
  ast: 'Asturian (Asturianu)',
  az: 'Azerbaijani (Az&#x259;rbaycanca)',
  bn: 'Bangla (&#x9AC;&#x9BE;&#x982;&#x9B2;&#x9BE;)',
  ba: 'Bashkir (&Bcy;&acy;&shcy;&#x4A1;&ocy;&rcy;&tcy;&scy;&acy;)',
  eu: 'Basque (Euskara)',
  be: 'Belarusian (&Bcy;&iecy;&lcy;&acy;&rcy;&ucy;&scy;&kcy;&acy;&yacy;)',
  br: 'Breton (Brezhoneg)',
  bg: 'Bulgarian (&Bcy;&hardcy;&lcy;&gcy;&acy;&rcy;&scy;&kcy;&icy;)',
  ca: 'Catalan (Catal&agrave;)',
  'zh-cn': 'Chinese Simplified (&#x7B80;&#x4F53;&#x4E2D;&#x6587;)',
  'zh-tw': 'Chinese Traditional (&#x7E41;&#x9AD4;&#x4E2D;&#x6587;)',
  co: 'Corsican (Corsu)',
  hr: 'Croatian (Hrvatski)',
  cs: 'Czech (&Ccaron;e&scaron;tina)',
  da: 'Danish (Dansk)',
  nl: 'Dutch (Nederlands)',
  en: 'English (English)',
  eo: 'Esperanto (Esperanto)',
  et: 'Estonian (eesti keel)',
  ext: 'Extremaduran (Estreme&ntilde;u)',
  fa: 'Farsi (&#x641;&#x627;&#x631;&#x633;&#x6CC;)',
  fi: 'Finnish (Suomi)',
  fr: 'French (Fran&ccedil;ais)',
  fy: 'Frisian (Frysk)',
  fur: 'Friulian (Furlan)',
  gl: 'Galician (Galego)',
  ka: 'Georgian (&#x10E5;&#x10D0;&#x10E0;&#x10D7;&#x10E3;&#x10DA;&#x10D8;)',
  de: 'German (Deutsch)',
  el: 'Greek (&Epsilon;&lambda;&lambda;&eta;&nu;&iota;&kappa;&#x3AC;)',
  gu: 'Gujarati, Indian, &#xAB9;&#xABF;&#xAA8;&#xACD;&#xAA6;&#xAC1;&#xAB8;&#xACD;&#xAA4;&#xABE;&#xAA8; (&#xA97;&#xAC1;&#xA9C;&#xAB0;&#xABE;&#xAA4;&#xAC0;)',
  he: 'Hebrew (&#x5E2;&#x5D1;&#x5E8;&#x5D9;&#x5EA;)',
  hi: 'Hindi, Indian, &#x939;&#x93F;&#x928;&#x94D;&#x926;&#x941;&#x938;&#x94D;&#x924;&#x93E;&#x928; (&#x939;&#x93F;&#x928;&#x94D;&#x926;&#x940;)',
  hu: 'Hungarian (Magyar)',
  is: 'Icelandic (&Iacute;slenska)',
  io: 'Ido (Ido)',
  id: 'Indonesian (Bahasa Indonesia)',
  ga: 'Irish (Gaeilge)',
  it: 'Italian (Italiano)',
  ja: 'Japanese (&#x65E5;&#x672C;&#x8A9E;)',
  kaa: 'Karakalpak - Latin (Qaraqalpaqsha - Lat&imath;n)',
  kk: 'Kazakh (&#x49A;&acy;&zcy;&acy;&#x49B;&shcy;&acy;)',
  ko: 'Korean (&#xD55C;&#xAD6D;&#xC5B4;)',
  'ku-ckb': 'Kurdish - Sorani (&#x6A9;&#x648;&#x631;&#x62F;&#x6CC;)',
  ku: 'Kurdish (Kurd&icirc;)',
  ky: 'Kyrgyz (&Kcy;&ycy;&rcy;&gcy;&ycy;&zcy;&chcy;&acy;)',
  lv: 'Latvian (Latvie&scaron;u)',
  lij: 'Ligurian (Zeneize)',
  lt: 'Lithuanian (Lietuvi&uogon;)',
  mk: 'Macedonian (&Mcy;&acy;&kcy;&iecy;&dcy;&ocy;&ncy;&scy;&kcy;&icy;)',
  ms: 'Malay (Bahasa Melayu)',
  mr: 'Marathi (&#x92E;&#x930;&#x93E;&#x920;&#x940;)',
  mng2: 'Mongolian (MenkCode) (&#xE5EB;&#xE5D6;&#xE5CF;&#xE5EA;&#xE5DA;&#xE5DA;&#xE5D6;&#xE5F0; &#xE5E5;&#xE5CF;&#xE5F1;&#xE5CC;)',
  mng: 'Mongolian (Unicode) (&#x182E;&#x1824;&#x1829;&#x182D;&#x1824;&#x182F; &#x182C;&#x1821;&#x182F;&#x1821;)',
  mn: 'Mongolian (&Mcy;&ocy;&ncy;&gcy;&ocy;&lcy; &khcy;&ecy;&lcy;)',
  ne: 'Nepali (&#x928;&#x947;&#x92A;&#x93E;&#x932;&#x940;)',
  nb: 'Norwegian Bokmal (Norsk Bokm&aring;l)',
  nn: 'Norwegian Nynorsk (Norsk Nynorsk)',
  ps: 'Pashto (&#x67E;&#x69A;&#x62A;&#x648;)',
  pl: 'Polish (Polski)',
  'pt-br': 'Portuguese Brazilian (Portugu&ecirc;s Brasileiro)',
  pt: 'Portuguese Portugal (Portugu&ecirc;s)',
  'pa-in': 'Punjabi, Indian (&#xA2A;&#xA70;&#xA1C;&#xA3E;&#xA2C;&#xA40;)',
  ro: 'Romanian (Rom&acirc;n&abreve;)',
  ru: 'Russian (&Rcy;&ucy;&scy;&scy;&kcy;&icy;&jcy;)',
  sa: 'Sanskrit, Indian, &#x939;&#x93F;&#x928;&#x94D;&#x926;&#x941;&#x938;&#x94D;&#x924;&#x93E;&#x928;&#x902; (&#x938;&#x902;&#x938;&#x94D;&#x915;&#x943;&#x924;)',
  'sr-spc': 'Serbian - Cyrillic (&Scy;&rcy;&pcy;&scy;&kcy;&icy; - &tshcy;&icy;&rcy;&icy;&lcy;&icy;&tscy;&acy;)',
  'sr-spl': 'Serbian - Latin (Srpski - latinica)',
  si: 'Sinhala (&#xDC3;&#xDD2;&#xD82;&#xDC4;&#xDBD;)',
  sk: 'Slovak (Sloven&ccaron;ina)',
  sl: 'Slovenian (Slovenski)',
  es: 'Spanish (Espa&ntilde;ol)',
  sv: 'Swedish (Svenska)',
  ta: 'Tamil (&#xBA4;&#xBAE;&#xBBF;&#xBB4;&#xBCD;)',
  tt: 'Tatar (&Tcy;&acy;&tcy;&acy;&rcy;&chcy;&acy;)',
  th: 'Thai (&#xE44;&#xE17;&#xE22;)',
  tr: 'Turkish (T&uuml;rk&ccedil;e)',
  uk: 'Ukrainian (&Ucy;&kcy;&rcy;&acy;&yicy;&ncy;&scy;&softcy;&kcy;&acy;)',
  ug: 'Uyghur (&#x626;&#x6C7;&#x64A;&#x63A;&#x6C7;&#x631;&#x686;&#x6D5;)',
  uz: 'Uzbek (O\'zbek)',
  va: 'Valencian (Valenci&agrave;)',
  vi: 'Vietnamese (Ti&#x1EBF;ng Vi&#x1EC7;t)',
  cy: 'Welsh (Cymraeg)',
  yo: 'Yoruba (Yoruba)'
};
